# Generated by Django 4.1.4 on 2023-01-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_email', models.CharField(max_length=50)),
                ('customer_password', models.CharField(max_length=30)),
                ('customer_address', models.CharField(max_length=300)),
                ('customer_phoneno', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=18)),
                ('address', models.CharField(max_length=200)),
                ('account_holder_name', models.CharField(max_length=60)),
                ('ifsc_code', models.CharField(max_length=50)),
                ('bank_branch', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('seller_username', models.CharField(max_length=30)),
                ('seller_password', models.CharField(max_length=50)),
                ('seller_pic', models.ImageField(upload_to='seller/')),
            ],
        ),
    ]
