# Generated by Django 4.1.4 on 2023-01-10 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('product_no', models.CharField(max_length=18)),
                ('description', models.CharField(max_length=200)),
                ('price', models.FloatField(max_length=60)),
                ('current_stock', models.CharField(max_length=50)),
                ('product_pic', models.ImageField(upload_to='product/')),
                ('seller_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='common.seller')),
            ],
        ),
    ]
