# Generated by Django 4.1.4 on 2023-03-14 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, max_length=50)),
                ('customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='common.customer')),
                ('products', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='seller.product')),
            ],
        ),
    ]
